04-19 21:00:43 ERROR [31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/app/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 598, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/app/couchpotato/libs/requests/sessions.py", line 194, in resolve_redirects
    **adapter_kwargs
  File "/app/couchpotato/libs/requests/sessions.py", line 571, in send
    adapter = self.get_adapter(url=request.url)
  File "/app/couchpotato/libs/requests/sessions.py", line 645, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:3B5566CEDF9C3BA0037652BB8DDF964760980B6B&dn=Hellboy+%282019%29%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Telugu+%2B++Eng%5D+-+x264+-+1GB%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2780%2Fannounce&tr=udp%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.port443.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.justseed.it%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce'
[0m
04-19 21:00:43 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/dl/limetorrents/?jackett_apikey=47jjl4xrn810bql34j8vrko315ofvh4b&path=Q2ZESjhIQ255cDBQNFE1TnR3MjFsNThZUllOUVZEU2hyQVdPOGQ0WnFITGxIZGJ0cUlZb3V2LTNGdmRiOWNNOElyMU5PUjBaNlNkaWlKU1pNbnV5ai01VjlFTHhLa2Q4a2NIRWN4UVVUNGpFckcwMlhwejUzNWI0RVdqZjZHcTd3SzdieUVDU28xeXE4ek85VFVQZEJTLTFYcWN2bGprd2VfSEE3U3VQczlTYlJkMjlnTlFTYUU2WFc4TlU3MTlKOWF4QVB6aG5VR040ZENQSHU0b0VBNjlPaHV4R0UxZ2otZmh1Z3hKYXdkdXM2MXNGbTBqblE1Y1FSd0JsbUpRTFpBdmxFSGxKYmgyYzRIY01RV1MxdzhmS19HQQ&file=Hellboy+(2019)%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BHindi+%2B+Eng%5D+-+x264+-+800MB%5D, data: [][0m
04-19 21:00:45 ERROR [31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/app/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 598, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/app/couchpotato/libs/requests/sessions.py", line 194, in resolve_redirects
    **adapter_kwargs
  File "/app/couchpotato/libs/requests/sessions.py", line 571, in send
    adapter = self.get_adapter(url=request.url)
  File "/app/couchpotato/libs/requests/sessions.py", line 645, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:BFF5381CD426E24284D42DFBE5D05B04A768074C&dn=Hellboy+%282019%29%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BHindi+%2B+Eng%5D+-+x264+-+800MB%5D&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2780%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2740%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2750%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2740%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2Ftracker.port443.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.justseed.it%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce'
[0m
04-19 21:00:45 INFO [0m[core.media.movie.searcher] Search for Joker in Screener[0m
04-19 21:00:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt7286456&internal=False, data: [][0m
04-19 21:00:45 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:00:45 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:00:46 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:00:46 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:00:46 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:00:48 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:00:50 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:00:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:00:51 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:01:16 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:01:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:01:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:01:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:01:50 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:01:54 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:01:56 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:01:57 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-19 21:01:58 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/joker-2019/se/desc/1/, data: [][0m
04-19 21:01:58 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Joker+2019%22/0/7/201, data: [][0m
04-19 21:01:58 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-19 21:01:59 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i7286456/, data: [][0m
04-19 21:01:59 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt7286456&limit=10&page=1, data: [][0m
04-19 21:02:01 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt7286456&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-19 21:02:01 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-19 21:02:01 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt7286456&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:02:01 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=7286456&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-19 21:02:31 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4b08cd0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-19 21:02:31 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 720p[0m
04-19 21:02:31 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:02:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:02:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6612630&internal=False, data: [][0m
04-19 21:02:32 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:02:32 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:02:32 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:02:35 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:02:37 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:02:37 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:02:38 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:02:58 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:02:59 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:03:01 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:03:31 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:03:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:03:33 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:03:35 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:03:36 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:03:37 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:03:37 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/207, data: [][0m
04-19 21:03:37 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6612630/, data: [][0m
04-19 21:03:37 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-19 21:03:37 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6612630&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-19 21:03:37 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-19 21:03:37 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-19 21:03:38 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:03:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-19 21:03:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=3000&adv_age=1500&max=400&xmaxsize=10000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:03:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6612630&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-19 21:04:09 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4ba3a90>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-19 21:04:09 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 1080p[0m
04-19 21:04:09 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:04:09 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:04:09 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:04:09 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:04:09 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:04:09 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:04:10 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:04:10 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:04:39 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:04:39 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:04:39 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-19 21:04:39 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-19 21:04:41 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:04:41 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-19 21:04:41 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=4000&adv_age=1500&max=400&xmaxsize=20000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:05:11 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4601550>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-19 21:05:11 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Rip[0m
04-19 21:05:11 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:05:11 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:05:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:05:11 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:05:11 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:05:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:05:12 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:05:12 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:05:41 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:05:41 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:05:41 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201,207, data: [][0m
04-19 21:05:41 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-19 21:05:41 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-19 21:05:42 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:05:43 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-19 21:05:43 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=700&adv_age=1500&max=400&xmaxsize=7000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:06:13 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb49602f0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-19 21:06:13 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Disk[0m
04-19 21:06:13 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:06:13 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:06:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:06:14 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:06:14 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:06:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:06:15 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:06:15 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:06:44 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:06:44 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:06:44 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-19 21:06:44 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-19 21:06:45 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:06:46 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-19 21:06:46 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=20000&adv_age=1500&max=400&xmaxsize=60000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:07:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4a91810>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-19 21:07:16 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-Rip[0m
04-19 21:07:16 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:07:16 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:07:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:07:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:07:16 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:07:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:07:17 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:07:17 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:07:46 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:07:46 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:07:46 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201, data: [][0m
04-19 21:07:46 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-19 21:07:46 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-19 21:07:47 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:07:48 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=2400&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:07:48 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-R[0m
04-19 21:07:48 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6612630&internal=False, data: [][0m
04-19 21:07:48 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:07:48 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:07:48 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:07:48 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:07:48 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:07:48 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:07:48 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:07:49 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:08:18 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:08:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:08:19 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/202, data: [][0m
04-19 21:08:19 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-19 21:08:19 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-19 21:08:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:08:20 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in Screener[0m
04-19 21:08:20 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:08:20 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:08:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:08:20 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:08:20 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:08:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:08:20 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:08:20 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:08:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-19 21:08:50 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:08:50 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-19 21:08:50 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6612630/, data: [][0m
04-19 21:08:50 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6612630&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-19 21:08:52 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-19 21:09:21 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Yts: https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='yts.am', port=443): Read timed out. (read timeout=30)
[0m
04-19 21:09:21 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Rarbg: https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6612630&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='torrentapi.org', port=443): Read timed out. (read timeout=30)
[0m
04-19 21:09:21 ERROR [31m[hpotato.core.plugins.base] Failed opening url in KickAssTorrents: http://katcr.to/span/m-i6612630/ Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='katcr.to', port=443): Read timed out. (read timeout=30)
[0m
04-19 21:09:21 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:09:21 INFO [0m[core.media.movie.searcher] Search for Ad Astra in Screener[0m
04-19 21:09:21 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:09:21 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt2935510&internal=False, data: [][0m
04-19 21:09:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:09:22 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:09:23 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:09:23 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:09:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:09:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:09:27 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:09:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:09:29 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:09:30 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:09:33 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:10:03 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:10:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:10:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:10:09 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:10:10 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-19 21:10:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/a/ad-astra-2019/se/desc/1/, data: [][0m
04-19 21:10:11 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Ad+Astra+2019%22/0/7/201, data: [][0m
04-19 21:10:11 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt2935510&limit=10&page=1, data: [][0m
04-19 21:10:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i2935510/, data: [][0m
04-19 21:10:11 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt2935510&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-19 21:10:12 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-19 21:10:12 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-19 21:10:12 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=2935510&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-19 21:10:12 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt2935510&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:10:14 INFO [0m[core.media.movie.searcher] Search for John Wick: Chapter 3 – Parabellum in Screener[0m
04-19 21:10:14 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:10:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:10:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6146586&internal=False, data: [][0m
04-19 21:10:14 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:10:14 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:10:14 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:10:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:10:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:10:20 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:10:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:10:41 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:10:42 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:10:46 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:11:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:11:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:11:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:11:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:11:23 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-19 21:11:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-parabellum-2019/se/desc/1/, data: [][0m
04-19 21:11:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019%22/0/7/201, data: [][0m
04-19 21:11:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6146586/, data: [][0m
04-19 21:11:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6146586&limit=10&page=1, data: [][0m
04-19 21:11:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6146586&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-19 21:11:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/, data: [][0m
04-19 21:11:26 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/ Traceback (most recent call last):
HTTPError: 404 Client Error: Not Found for url: https://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/
[0m
04-19 21:11:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6146586&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:11:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6146586&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-19 21:11:28 INFO [0m[core.media.movie.searcher] Search for Midsommar in Screener[0m
04-19 21:11:28 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-19 21:11:28 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt8772262&internal=False, data: [][0m
04-19 21:11:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:11:29 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-19 21:11:29 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-19 21:11:29 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:11:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:11:33 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:11:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:11:34 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:11:57 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-19 21:11:58 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:12:00 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:12:30 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:12:30 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:12:35 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:12:36 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:12:38 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-19 21:12:39 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/m/midsommar-2019/se/desc/1/, data: [][0m
04-19 21:12:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Midsommar+2019%22/0/7/201, data: [][0m
04-19 21:12:39 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i8772262/, data: [][0m
04-19 21:12:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt8772262&limit=10&page=1, data: [][0m
04-19 21:12:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt8772262&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-19 21:12:40 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt8772262&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-19 21:12:40 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=8772262&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-19 21:13:10 ERROR [31m[hpotato.core.plugins.base] Failed opening url in BinSearch: https://www.binsearch.info/index.php?q=tt8772262&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.binsearch.info', port=443): Read timed out. (read timeout=30)
[0m
04-19 22:48:10 ERROR [31m[tato.core.plugins.renamer] The to folder "" doesn't exist. Please create it.[0m
04-20 00:48:10 ERROR [31m[tato.core.plugins.renamer] The to folder "" doesn't exist. Please create it.[0m
04-20 00:58:00 INFO [0m[core.media.movie.searcher] Search for Ad Astra in Screener[0m
04-20 00:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 00:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt2935510&internal=False, data: [][0m
04-20 00:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:58:01 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 00:58:01 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 00:58:01 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 00:58:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:58:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:58:27 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:58:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:58:51 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 00:58:52 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:58:55 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:59:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:59:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:59:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:59:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-20 00:59:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Ad+Astra+2019%22/0/7/201, data: [][0m
04-20 00:59:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/a/ad-astra-2019/se/desc/1/, data: [][0m
04-20 00:59:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i2935510/, data: [][0m
04-20 00:59:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt2935510&limit=10&page=1, data: [][0m
04-20 00:59:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-20 00:59:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in ThePirateBay: https://pirateproxy.cat/search/%22Ad+Astra+2019%22/0/7/201 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='pirateproxy.lat', port=443): Read timed out. (read timeout=30)
[0m
04-20 00:59:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in KickAssTorrents: http://katcr.to/span/m-i2935510/ Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='katcr.to', port=443): Read timed out. (read timeout=30)
[0m
04-20 00:59:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/a/ad-astra-2019/se/desc/1/ Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.magnetdl.com', port=443): Read timed out. (read timeout=30)
[0m
04-20 00:59:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Yts: https://yts.am/api/v2/list_movies.json?query_term=tt2935510&limit=10&page=1 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='yts.am', port=443): Read timed out. (read timeout=30)
[0m
04-20 00:59:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Rarbg: https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='torrentapi.org', port=443): Read timed out. (read timeout=30)
[0m
04-20 00:59:50 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt2935510&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-20 00:59:51 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-20 00:59:51 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-20 00:59:51 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-20 00:59:51 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt2935510&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 00:59:51 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=2935510&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-20 01:00:21 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb3e77f10>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-20 01:00:21 INFO [0m[core.media.movie.searcher] Search for Joker in Screener[0m
04-20 01:00:21 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:00:21 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt7286456&internal=False, data: [][0m
04-20 01:00:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:00:22 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:00:22 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:00:22 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:00:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:00:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:00:27 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:00:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:00:49 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:00:50 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:01:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:01:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:01:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:01:23 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-20 01:01:24 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/joker-2019/se/desc/1/, data: [][0m
04-20 01:01:24 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-20 01:01:24 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Joker+2019%22/0/7/201, data: [][0m
04-20 01:01:24 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i7286456/, data: [][0m
04-20 01:01:24 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt7286456&limit=10&page=1, data: [][0m
04-20 01:01:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt7286456&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-20 01:01:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-20 01:01:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt7286456&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:01:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=7286456&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-20 01:01:57 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4bd76b0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-20 01:01:57 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 720p[0m
04-20 01:01:57 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:01:57 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6612630&internal=False, data: [][0m
04-20 01:01:57 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:01:58 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:01:58 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:01:58 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:02:00 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:02 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:03 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:23 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:02:24 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:55 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:56 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:02:58 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:03:01 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6612630/, data: [][0m
04-20 01:03:01 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/207, data: [][0m
04-20 01:03:01 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-20 01:03:01 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:03:01 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6612630&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-20 01:03:01 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-20 01:03:01 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-20 01:03:02 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:03:02 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-20 01:03:02 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=3000&adv_age=1500&max=400&xmaxsize=10000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:03:02 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6612630&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-20 01:03:32 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb3ea2870>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-20 01:03:33 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 1080p[0m
04-20 01:03:33 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:03:33 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:03:33 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:03:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:03:33 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:03:34 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:03:34 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:03:34 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:03:34 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-20 01:03:34 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-20 01:03:35 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:03:35 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-20 01:03:35 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=4000&adv_age=1500&max=400&xmaxsize=20000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:04:05 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4b08890>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-20 01:04:05 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Rip[0m
04-20 01:04:05 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:04:05 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:04:05 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:04:06 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:04:06 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:04:06 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:04:06 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:04:06 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:04:06 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201,207, data: [][0m
04-20 01:04:06 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-20 01:04:06 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-20 01:04:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:04:07 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-20 01:04:07 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=700&adv_age=1500&max=400&xmaxsize=7000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:04:37 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb3ea2eb0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-20 01:04:37 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Disk[0m
04-20 01:04:37 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:04:38 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:04:38 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:04:38 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:04:38 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:04:38 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:04:38 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:04:38 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:04:38 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-20 01:04:38 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-20 01:04:40 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:04:40 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-20 01:04:40 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=20000&adv_age=1500&max=400&xmaxsize=60000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:05:10 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4bce890>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-20 01:05:10 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-Rip[0m
04-20 01:05:10 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:05:10 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:05:10 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:05:10 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:05:10 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:05:10 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:05:10 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:05:10 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:05:11 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201, data: [][0m
04-20 01:05:11 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-20 01:05:11 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-20 01:05:12 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:05:12 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=2400&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:05:13 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-R[0m
04-20 01:05:13 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:05:13 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:05:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:05:13 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:05:13 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:05:13 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:05:13 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:05:13 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/202, data: [][0m
04-20 01:05:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:05:13 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-20 01:05:13 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-20 01:05:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:05:15 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in Screener[0m
04-20 01:05:15 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:05:15 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:05:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:05:15 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-20 01:05:15 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:05:15 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:05:15 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:05:15 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-20 01:05:15 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-20 01:05:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:05:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-20 01:05:17 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:05:18 INFO [0m[core.media.movie.searcher] Search for Hellboy in Screener[0m
04-20 01:05:18 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:05:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt2274648&internal=False, data: [][0m
04-20 01:05:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:05:18 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:05:18 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:05:19 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:05:22 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:05:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:05:26 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:05:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:05:27 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:05:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:05:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:06:01 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:06:06 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:06:07 INFO [0m[edia._base.providers.base] Found: score(1596) on TorrentPotato, 10.0.0.12: Hellboy (2019)[HQ DVDScr - HQ Line Audios - [Tamil + Telugu] - XviD - MP3 - 700M..[LimeTorrents][0m
04-20 01:06:07 INFO [0m[edia._base.providers.base] Found: score(1499) on TorrentPotato, 10.0.0.12: Hellboy (2019)[720p - HQ DVDScr - HQ Line Audios - [Tamil + Telugu + Hindi + Eng..[LimeTorrents][0m
04-20 01:06:08 INFO [0m[edia._base.providers.base] Found: score(1103) on TorrentPotato, 10.0.0.12: Hellboy (2019)[720p - HQ DVDScr - HQ Line Audios - [Tamil + Eng] - x264 - 900MB][LimeTorrents][0m
04-20 01:06:09 INFO [0m[edia._base.providers.base] Found: score(542) on TorrentPotato, 10.0.0.12: Hellboy (2019)[720p - HQ DVDScr - HQ Line Audios - [Tamil + Telugu + Eng] - x26..[LimeTorrents][0m
04-20 01:06:10 INFO [0m[edia._base.providers.base] Found: score(427) on TorrentPotato, 10.0.0.12: Hellboy (2019)[720p - HQ DVDScr - HQ Line Audios - [Hindi + Eng] - x264 - 800MB][LimeTorrents][0m
04-20 01:06:10 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:06:12 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt2274648&search=Hellboy+2019&user=&passkey=xxx[0m
04-20 01:06:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Hellboy+2019%22/0/7/201, data: [][0m
04-20 01:06:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/h/hellboy-2019/se/desc/1/, data: [][0m
04-20 01:06:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i2274648/, data: [][0m
04-20 01:06:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt2274648&limit=10&page=1, data: [][0m
04-20 01:06:15 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt2274648&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-20 01:06:16 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt2274648&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:06:16 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=2274648&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-20 01:06:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/dl/limetorrents/?jackett_apikey=47jjl4xrn810bql34j8vrko315ofvh4b&path=Q2ZESjhIQ255cDBQNFE1TnR3MjFsNThZUllQXzRQMHpnbnc5aWVWRm1odE9OTzVOMUlJV0F3QmpqZ1JQWDFyQjhlTlBHdFJWQTNqSGU0VkZTekJPTUl6UURidHF1WXJhQXdqcS1GSzhTcURkRHhHbEdjbGJiQWdoS0lBQXRhWkVaU05HOUJrdE1xeDJzdDl0czREeUFFSTR0enZpbEd2V1BvdnRLaFRhM1huT3VDdWRiQUZONVVKRktGUlNMWDNJT1dYVG1SRngyTG5lczhMUUs1QXdzV25DVWpmX3ZyX2pPMEtENWV2N1lvSU1XWGNhOHBzY1VMRmI0X0xOUzZCVnJrVEthdG5tT0tVMjB0VExoSlNNQzlrdXF5ZEVmeXBCSDNVZHlJT2V3c2J5b243MA&file=Hellboy+(2019)%5BHQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Telugu%5D+-+XviD+-+MP3+-+700M.., data: [][0m
04-20 01:06:19 ERROR [31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/app/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 598, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/app/couchpotato/libs/requests/sessions.py", line 194, in resolve_redirects
    **adapter_kwargs
  File "/app/couchpotato/libs/requests/sessions.py", line 571, in send
    adapter = self.get_adapter(url=request.url)
  File "/app/couchpotato/libs/requests/sessions.py", line 645, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:5F06B826F270DAB1370EB2369FA4CEAEC734A675&dn=Hellboy+%282019%29%5BHQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Telugu%5D+-+XviD+-+MP3+-+700MB%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.port443.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.justseed.it%3A1337%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce'
[0m
04-20 01:06:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/dl/limetorrents/?jackett_apikey=47jjl4xrn810bql34j8vrko315ofvh4b&path=Q2ZESjhIQ255cDBQNFE1TnR3MjFsNThZUllQd0JZS2k5MjliVGhLd3ZtTjhvSGJTNDhWNWtnSjV2RDJwcXZ1bTVkQmVOd1ZVcnlXczRBOTJoNS1md0lvaWVNTm1jWnp0dGpfcVBvZFpVMTlQVUgyMGVuLUhKdExBVUQwX2Z5YzdsTWRBcUFHazlQVzh5UmVSUXlYc2dLbnVtZ0JteXFydHVsMGVRbjU5OUFRdUJEYVVsenRDMXZSMkJlUlpadjNDX2tJNmtkaWxWSjVaOGJqcjZ5Y21EUDZWeDdnWklsdTV5Tmw3c1JrOUhBdTNVY19VRFc5NFFKaXVmZ2lWUjNrSWpnRjV4bzhpYUJEYXFPVy13UkNTTXcxQ1FOaEw3aVlrQWdmTWlxQzYwVm8wZzcxWQ&file=Hellboy+(2019)%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Telugu+%2B+Hindi+%2B+Eng.., data: [][0m
04-20 01:06:20 ERROR [31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/app/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 598, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/app/couchpotato/libs/requests/sessions.py", line 194, in resolve_redirects
    **adapter_kwargs
  File "/app/couchpotato/libs/requests/sessions.py", line 571, in send
    adapter = self.get_adapter(url=request.url)
  File "/app/couchpotato/libs/requests/sessions.py", line 645, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:C3270EC47415C5255E03AA401977F22F747D6AB1&dn=Hellboy+%282019%29%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Telugu+%2B+Hindi+%2B+Eng%5D+-+x264+-+1GB%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2740%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2740%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.port443.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.justseed.it%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce'
[0m
04-20 01:06:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/dl/limetorrents/?jackett_apikey=47jjl4xrn810bql34j8vrko315ofvh4b&path=Q2ZESjhIQ255cDBQNFE1TnR3MjFsNThZUllPRXVoTGdXWFJWVS1xWUZFSGZYWEI5NEFLQm9XMHROWlNfcmQwUFMwdVVEMnpOU2ZZaG1fSV9WSENWNUhPMjNKQTZWZm5fQXZ2REFoN3FaUk1ITUdYWjdBbVNCMDZhY292b3IxMDNpb3VXX0NWYjZtN1lyQ1BpMkVGTmxqdmxKcVZMVXZxVGVsUFp4aVlZMnNCSXgwdWpfN21xSGs4cnZnMzVxX1ZyTHhhSThEWE1Jc2ZucHZ3Qm5RYnVRNEN0dEZEdkRKTVloUjBPNTRkdjlrRzBMdWFPZnBvSlQxRXB5ZnFjejdjV2I4T1dhUVRZajJpaVB1M0xOSXNzWjZ1YnZxaw&file=Hellboy+(2019)%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Eng%5D+-+x264+-+900MB%5D, data: [][0m
04-20 01:06:21 ERROR [31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/app/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 598, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/app/couchpotato/libs/requests/sessions.py", line 194, in resolve_redirects
    **adapter_kwargs
  File "/app/couchpotato/libs/requests/sessions.py", line 571, in send
    adapter = self.get_adapter(url=request.url)
  File "/app/couchpotato/libs/requests/sessions.py", line 645, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:4DE414EE9C2B7F3E5FD36F143ED365C8814C79D8&dn=Hellboy+%282019%29%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Eng%5D+-+x264+-+900MB%5D&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2780%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2740%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2800%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2740%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.port443.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.justseed.it%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce'
[0m
04-20 01:06:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/dl/limetorrents/?jackett_apikey=47jjl4xrn810bql34j8vrko315ofvh4b&path=Q2ZESjhIQ255cDBQNFE1TnR3MjFsNThZUllPSEFiYkhCSmRwT0c4NGIxaElWNUVneVVMaHFITmMxakNmVlNrVlc2N2owVUllN3d5REZPMUt0aFVGQmF4N01mb2l4MElwOFA0dE5kbXlXNk80Q3pGSHR4bTBFVXRLRWNsdEVHMDBrZVdmeDgwUVFqMkpfRFc0aDZpNU5KS2ZRemNTT3A4eHFIV2tVXzdGOXBPTkxFVk9YN0s5TWxnZUtRemJpdlpLdUh5OVNNM0RvaFZCdHFsN2RUN0pSWUJ1cXFLX2hUcnlHUS13T1FGd1Q5Vl8ySDY0bEluQU9LNDYyTl9FbXk2Z3prNHlISTlyVUdtQTlpNTBfX3dtekdMNWFERVNrTWY1dzMyVS1BZUJyc1BEekFxeA&file=Hellboy+(2019)%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Telugu+%2B+Eng%5D+-+x26.., data: [][0m
04-20 01:06:22 ERROR [31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/app/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 598, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/app/couchpotato/libs/requests/sessions.py", line 194, in resolve_redirects
    **adapter_kwargs
  File "/app/couchpotato/libs/requests/sessions.py", line 571, in send
    adapter = self.get_adapter(url=request.url)
  File "/app/couchpotato/libs/requests/sessions.py", line 645, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:3B5566CEDF9C3BA0037652BB8DDF964760980B6B&dn=Hellboy+%282019%29%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BTamil+%2B+Telugu+%2B++Eng%5D+-+x264+-+1GB%5D&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2F9.rarbg.com%3A2780%2Fannounce&tr=udp%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.port443.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.justseed.it%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce'
[0m
04-20 01:06:22 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/dl/limetorrents/?jackett_apikey=47jjl4xrn810bql34j8vrko315ofvh4b&path=Q2ZESjhIQ255cDBQNFE1TnR3MjFsNThZUllQMmY0SWxManpKSWRKRnUtVlhORnRUek9LTGhSTEczRk1Rd0RqQnZscG85V1lZeUVJUGp3Q19kb1UyLV93ZDRMTnhOQ3BENnc2ME11YlN6Z0w5MFlnU1NsV1lobE1CM282WGltWV8tSlNMWk9mT1Z0QlFqZFROM1djcEh1SV9HaFoxQkpNTWt4ZmF4Y1NSMmhwYk5MT1ZtRF9nYTJPc21QV0RCOC1rSWx3b2JOTjN5VUVhd25YeTU2cjRtRThFR3FzSXRFdjJwalc5eWl4S2xKR0l6WGw0QTFwTHRwbVp3TFlla2FMaXRTbGpHZEVvR2xKNThQT1hXb1lWTEIwaW1FVQ&file=Hellboy+(2019)%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BHindi+%2B+Eng%5D+-+x264+-+800MB%5D, data: [][0m
04-20 01:06:23 ERROR [31m[edia._base.providers.base] Failed getting release from TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 207, in download
    return self.urlopen(url, headers = {'User-Agent': Env.getIdentifier()}, show_error = False)
  File "/app/couchpotato/couchpotato/core/plugins/base.py", line 221, in urlopen
    response = r.request(method, url, **kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 469, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/couchpotato/libs/requests/sessions.py", line 598, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/app/couchpotato/libs/requests/sessions.py", line 194, in resolve_redirects
    **adapter_kwargs
  File "/app/couchpotato/libs/requests/sessions.py", line 571, in send
    adapter = self.get_adapter(url=request.url)
  File "/app/couchpotato/libs/requests/sessions.py", line 645, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
InvalidSchema: No connection adapters were found for 'magnet:?xt=urn:btih:BFF5381CD426E24284D42DFBE5D05B04A768074C&dn=Hellboy+%282019%29%5B720p+-+HQ+DVDScr+-+HQ+Line+Audios+-+%5BHindi+%2B+Eng%5D+-+x264+-+800MB%5D&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fthetracker.org%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv4.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2780%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2740%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2770%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2750%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2710%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2740%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2730%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2720%2Fannounce&tr=udp%3A%2F%2Ftracker.port443.xyz%3A6969%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.cyberia.is%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.justseed.it%3A1337%2Fannounce&tr=udp%3A%2F%2Fipv6.tracker.harry.lu%3A80%2Fannounce&tr=udp%3A%2F%2Fbt.xxx-tracker.com%3A2710%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.open-internet.nl%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.si%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.pirateparty.gr%3A6969%2Fannounce'
[0m
04-20 01:06:23 INFO [0m[core.media.movie.searcher] Search for Midsommar in Screener[0m
04-20 01:06:23 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:06:23 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt8772262&internal=False, data: [][0m
04-20 01:06:23 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:06:24 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:06:24 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:06:24 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:06:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:06:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:06:31 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:06:32 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:06:52 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:06:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:06:56 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:07:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:07:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:07:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:07:23 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-20 01:07:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/m/midsommar-2019/se/desc/1/, data: [][0m
04-20 01:07:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i8772262/, data: [][0m
04-20 01:07:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Midsommar+2019%22/0/7/201, data: [][0m
04-20 01:07:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt8772262&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-20 01:07:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt8772262&limit=10&page=1, data: [][0m
04-20 01:07:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt8772262&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:07:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=8772262&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-20 01:07:27 INFO [0m[core.media.movie.searcher] Search for John Wick: Chapter 3 – Parabellum in Screener[0m
04-20 01:07:27 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6146586&internal=False, data: [][0m
04-20 01:07:27 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-20 01:07:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:07:29 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-20 01:07:29 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-20 01:07:29 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:07:30 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:07:32 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:07:32 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.-ag0.12:9117/api/v2.0/indexers/extratorrent/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:07:33 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/anidex/results/torznab/api?apikey=xxx&t=search&cat=&q=?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:07:46 ERROR [31m[edia._base.providers.base] Failed to parsing TorrentPotato: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-20 01:07:47 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/isohunt2/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:07:51 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:08:21 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/katcrs/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:08:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/kickasstorrent/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:08:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/limetorrents/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:08:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/magnetdl/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:08:29 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/nyaasi/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-20 01:08:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-parabellum-2019/se/desc/1/, data: [][0m
04-20 01:08:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019%22/0/7/201, data: [][0m
04-20 01:08:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6146586/, data: [][0m
04-20 01:08:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6146586&limit=10&page=1, data: [][0m
04-20 01:08:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6146586&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-20 01:08:32 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/, data: [][0m
04-20 01:08:32 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/ Traceback (most recent call last):
HTTPError: 404 Client Error: Not Found for url: https://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/
[0m
04-20 01:08:32 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6146586&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-20 01:08:32 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6146586&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-20 02:48:10 ERROR [31m[tato.core.plugins.renamer] The to folder "" doesn't exist. Please create it.[0m
04-20 03:34:21 INFO [0m[chpotato.core._base._core] Shutting down[0m
04-20 03:34:21 INFO [0mShutting down thread pool[0m
